version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 3
    labels:
      - security
      - dependencies
    allow:
      - dependency-type: direct
    commit-message:
      prefix: chore
